# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(721, 321)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 721, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 4)
        self.update_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.update_btn.setObjectName("update_btn")
        self.gridLayout.addWidget(self.update_btn, 0, 3, 1, 1)
        self.create_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.create_btn.setObjectName("create_btn")
        self.gridLayout.addWidget(self.create_btn, 0, 0, 1, 1)
        self.change_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.change_btn.setObjectName("change_btn")
        self.gridLayout.addWidget(self.change_btn, 0, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.update_btn.setText(_translate("Form", "Обновить"))
        self.create_btn.setText(_translate("Form", "Создать"))
        self.change_btn.setText(_translate("Form", "Изменить"))
